//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TsID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int Passanger { get; set; }
        public int Flight { get; set; }
        public bool Type { get; set; }
        public int Employee { get; set; }
        public Nullable<int> Charges { get; set; }
        public Nullable<int> Discount { get; set; }
        public int Total { get; set; }
    
        public virtual Charge Charge { get; set; }
        public virtual Discount Discount1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Flight_Schedule Flight_Schedule { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
